


PROGRAM ZALV_PRG_26.










DATA: OK_CODE TYPE sy-ucomm.

DATA: BEGIN OF GS_DATA.
        INCLUDE TYPE SFLIGHT.
DATA: LIGHT TYPE C,
      COLOR TYPE CHAR4,
      ITCOL TYPE LVC_T_SCOL,
      END OF GS_DATA,

      GT_DATA LIKE TABLE OF GS_DATA.


DATA: GO_CON TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV TYPE REF TO CL_GUI_ALV_GRID,

      GS_VARIANT TYPE DISVARIANT,
      GS_LAYOUT TYPE LVC_S_LAYO,
      GT_SORT TYPE LVC_T_SORT,
      GT_FUNC TYPE UI_FUNCTIONS.



SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME.
  SELECT-OPTIONS: SO_CAR FOR GS_DATA-CARRID,
                  SO_CON FOR GS_DATA-CONNID.
SELECTION-SCREEN END OF BLOCK BLK1.
