FUNCTION Z_BC400_26_FLIGHTLIST_GET.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     REFERENCE(IV_CARRID) TYPE  S_CARR_ID
*"     REFERENCE(IV_CONNID) TYPE  S_CONN_ID
*"  EXPORTING
*"     REFERENCE(ET_FLIGHTS) TYPE  BC400_T_FLIGHTS
*"  EXCEPTIONS
*"      NO_DATA
*"----------------------------------------------------------------------

DATA : LS_FLIGHT LIKE LINE OF ET_FLIGHTS.




CLEAR ET_FLIGHTS.

SELECT * INTO CORRESPONDING FIELDS OF LS_FLIGHT
  FROM SFLIGHT
  WHERE CARRID = IV_CARRID
    AND CONNID = IV_CONNID.



  LS_FLIGHT-PERCENTAGE = LS_FLIGHT-SEATSOCC / LS_FLIGHT-SEATSMAX * 100.

  APPEND LS_FLIGHT TO ET_FLIGHTS.

ENDSELECT.



IF SY-SUBRC <> 0.
  RAISE NO_DATA.
ELSE.
  SORT ET_FLIGHTS BY PERCENTAGE DESCENDING.
ENDIF.


ENDFUNCTION.
