*&---------------------------------------------------------------------*
*& Report ZBC400_26_STRUCTURE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZBC400_26_STRUCTURE.



*----------------------------------------------------
*아래처럼 해야지 필드값 엔티티가 F4눌렀을 때 뜸
*BC400구조체는 STATIC STRUC으로써 더블클릭해서 보면 Search Help가 들어있땅!
PARAMETERS: PA_CAR TYPE bc400_s_flight-carrid,
            PA_CON TYPE bc400_s_flight-CONNID,
            PA_DATE TYPE bc400_s_flight-FLDATE.
*----------------------------------------------------
*PARAMETERS PA_CAR TYPE S_CARR_ID.
*PARAMETERS PA_CON TYPE S_CONN_ID.
*PARAMETERS PA_DATE TYPE S_DATE.
*----------------------------------------------------
*PARAMETERS : PA_CAR TYPE S_CARR_ID,
*             PA_CON TYPE S_CONN_ID,
*             PA_DATE TYPE S_DATE.

TYPES : BEGIN OF TS_CARRIER,
          CARRID TYPE S_CARR_ID,
          CARRNAME TYPE S_CARRNAME,
          CURRCODE TYPE S_CURRCODE,
          URL TYPE S_CARRURL,
        END OF TS_CARRIER.



TYPES : BEGIN OF TS_FLIGHT,
          CARRID TYPE S_CARR_ID,
          CONNID TYPE S_CONN_ID,
          FLDATE TYPE S_DATE,
          SEATSMAX TYPE S_SEATSMAX,
          SEATSOCC TYPE S_SEATSOCC,
          PERCENTAGE TYPE S_FLGHTOCC,
        END OF TS_FLIGHT.




TYPES : BEGIN OF TS_CARRIERFLIGHT,
          CARRID TYPE S_CARR_ID,
          CARRNAME TYPE S_CARRNAME,
          CURRCODE TYPE S_CURRCODE,
          URL TYPE S_CARRURL,
          CONNID TYPE S_CONN_ID,
          FLDATE TYPE S_DATE,
          SEATSMAX TYPE S_SEATSMAX,
          SEATSOCC TYPE S_SEATSOCC,
          PERCENTAGE TYPE S_FLGHTOCC,
        END OF TS_CARRIERFLIGHT.


DATA : GS_CARRIER TYPE TS_CARRIER.

DATA : GS_FLIGHT TYPE TS_FLIGHT.
*        GS_FLIGHT-CARRID = 'AA'.
*        GS_FLIGHT-CONNID = '0017'.
*        GS_FLIGHT-FLDATE = SY-DATUM.
*        GS_FLIGHT-SEATSMAX = 300.
*        GS_FLIGHT-SEATSOCC = 150.
*        GS_FLIGHT-PERCENTAGE = '50'.

DATA : GS_CARRIERFLIGHT TYPE TS_CARRIERFLIGHT.




*메서드 호출
TRY.

  CALL METHOD CL_BC400_FLIGHTMODEL=>GET_CARRIER
    EXPORTING
      IV_CARRID  = PA_CAR
    IMPORTING
      ES_CARRIER = GS_CARRIER
      .

  CALL METHOD CL_BC400_FLIGHTMODEL=>GET_FLIGHT
    EXPORTING
      IV_CARRID = PA_CAR
      IV_CONNID = PA_CON
      IV_FLDATE = PA_DATE
    IMPORTING
      ES_FLIGHT = GS_FLIGHT
      .
   CATCH CX_BC400_NO_DATA .
     MESSAGE 'DATA 가 없습니다' TYPE 'I'.
     RETURN.
   CATCH CX_BC400_NO_AUTH .
     MESSAGE 'AUTH 가 없습니다.' TYPE 'I'.
     RETURN.

ENDTRY.


WRITE:/.


*기존 값 출력
WRITE :/ 'GS_CARRIER 값 출력'.
WRITE :/ GS_CARRIER-CARRID.
WRITE GS_CARRIER-CARRNAME.
WRITE GS_CARRIER-CURRCODE.
WRITE GS_CARRIER-URL.

WRITE:/.

WRITE :/ 'GS_FLIGHT 값 출력'.
WRITE :/ GS_FLIGHT-CARRID.
WRITE GS_FLIGHT-CONNID.
WRITE GS_FLIGHT-FLDATE.
WRITE GS_FLIGHT-SEATSMAX.
WRITE GS_FLIGHT-SEATSOCC.
WRITE GS_FLIGHT-PERCENTAGE.


ULINE.

* 기존 CARRIER, FLIGHT에서 두개의 구조체가 가진것을 합친 구조체로 값 복사
MOVE-CORRESPONDING GS_CARRIER TO GS_CARRIERFLIGHT.
MOVE-CORRESPONDING GS_FLIGHT TO GS_CARRIERFLIGHT.





WRITE:/.


WRITE :/ 'GS_CARRIERFLIGHT 값 출력'.
* 옮겨졌는지 확인
WRITE :/ GS_CARRIERFLIGHT-CARRID.
WRITE GS_CARRIERFLIGHT-CARRNAME.
WRITE GS_CARRIERFLIGHT-CURRCODE.
WRITE GS_CARRIERFLIGHT-URL.
WRITE GS_CARRIERFLIGHT-CONNID.
WRITE GS_CARRIERFLIGHT-FLDATE.
WRITE GS_CARRIERFLIGHT-SEATSMAX.
WRITE GS_CARRIERFLIGHT-SEATSOCC.
WRITE GS_CARRIERFLIGHT-PERCENTAGE.
