FUNCTION ZCA_BILLINGDOC_GETLIST.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_SDDOC) TYPE  VBELN OPTIONAL
*"     VALUE(I_DLDOC) TYPE  VBELN OPTIONAL
*"     VALUE(I_BLDOC) TYPE  VBELN OPTIONAL
*"     VALUE(I_ITMNUM) TYPE  POSNR OPTIONAL
*"     VALUE(I_COMPANY) TYPE  BUKRS OPTIONAL
*"     VALUE(I_SALESORG) TYPE  VKORG OPTIONAL
*"     VALUE(I_PAYER) TYPE  KUNRG OPTIONAL
*"     VALUE(I_SOLDTO) TYPE  KUNAG OPTIONAL
*"     VALUE(I_MATERIAL) TYPE  MATNR OPTIONAL
*"     VALUE(I_OALLSTATUS) TYPE  GBSTK OPTIONAL
*"     VALUE(I_INVCSTATUS) TYPE  RELIK OPTIONAL
*"     VALUE(I_DOCDATE) TYPE  ZCA_DOCDATE_WA OPTIONAL
*"  EXPORTING
*"     VALUE(ET_BILLINGDOC) TYPE  ZCA_BILLINGDOC_TT
*"  TABLES
*"      T_DOCDATE TYPE  ZCA_DOCDATE_TT
*"----------------------------------------------------------------------

DATA: L_ITMNUM TYPE CHAR7,
      L_SDDOC  TYPE CHAR11,
      L_DLDOC  TYPE CHAR11,
      L_BLDOC  TYPE CHAR11.


I_DOCDATE-SIGN = 'I'.
I_DOCDATE-OPTION = 'BT'.

IF I_DOCDATE-SALES_DATE_LOW IS INITIAL.
  I_DOCDATE-SALES_DATE_LOW = '00000000'.
ENDIF.

IF I_DOCDATE-SALES_DATE_HIGH IS INITIAL.
  I_DOCDATE-SALES_DATE_HIGH = '99991231'.
ENDIF.


APPEND I_DOCDATE TO T_DOCDATE.
CLEAR I_DOCDATE.


IF I_SDDOC IS INITIAL.
  L_SDDOC = '%'.
ELSE.
  SHIFT I_SDDOC LEFT DELETING LEADING '0'.
  IF STRLEN( I_SDDOC ) < 10.
    CONCATENATE '%' I_SDDOC '%' INTO L_SDDOC.
  ENDIF.
ENDIF.



IF I_DLDOC IS INITIAL.
  L_DLDOC = '%'.
ELSE.
  SHIFT I_DLDOC LEFT DELETING LEADING '0'.
  IF STRLEN( I_DLDOC ) < 10.
    CONCATENATE '%' I_DLDOC '%' INTO L_DLDOC.
  ENDIF.
ENDIF.


IF I_BLDOC IS INITIAL.
  L_BLDOC = '%'.
ELSE.
  SHIFT I_BLDOC LEFT DELETING LEADING '0'.
  IF STRLEN( I_BLDOC ) < 10.
    CONCATENATE '%' I_BLDOC '%' INTO L_BLDOC.
  ENDIF.
ENDIF.








IF I_ITMNUM IS INITIAL.
  L_ITMNUM = '%'.
ELSE.
  L_ITMNUM = I_ITMNUM.
ENDIF.

IF I_COMPANY IS INITIAL.
  I_COMPANY = 'A001'."'%'.
ELSEIF STRLEN( I_COMPANY ) < 4.
  CONCATENATE I_COMPANY '%' INTO I_COMPANY.
  TRANSLATE I_COMPANY TO UPPER CASE.
ELSE.
  TRANSLATE I_COMPANY TO UPPER CASE.
ENDIF.

IF I_SALESORG IS INITIAL.
  I_SALESORG = '%'.
ELSEIF STRLEN( I_SALESORG ) < 4.
  CONCATENATE I_SALESORG '%' INTO I_SALESORG.
  TRANSLATE I_SALESORG TO UPPER CASE.
ELSE.
  TRANSLATE I_SALESORG TO UPPER CASE.
ENDIF.

IF I_PAYER IS INITIAL.
  I_PAYER = '%'.
ELSEIF STRLEN( I_PAYER ) < 10.
  CONCATENATE I_PAYER '%' INTO I_PAYER.
  TRANSLATE I_PAYER TO UPPER CASE.
ELSE.
  TRANSLATE I_PAYER TO UPPER CASE.
ENDIF.

IF I_SOLDTO IS INITIAL.
  I_SOLDTO = '%'.
ELSEIF STRLEN( I_SOLDTO ) < 10.
  CONCATENATE I_SOLDTO '%' INTO I_SOLDTO.
  TRANSLATE I_SOLDTO TO UPPER CASE.
ELSE.
  TRANSLATE I_SOLDTO TO UPPER CASE.
ENDIF.

IF I_MATERIAL IS INITIAL.
  I_MATERIAL = '%'.
ELSEIF STRLEN( I_MATERIAL ) < 40.
  CONCATENATE I_MATERIAL '%' INTO I_MATERIAL.
  TRANSLATE I_MATERIAL TO UPPER CASE.
ELSE.
  TRANSLATE I_MATERIAL TO UPPER CASE.
ENDIF.

IF I_OALLSTATUS IS INITIAL.
  I_OALLSTATUS = '%'.
ELSEIF I_OALLSTATUS = 'X'.
  I_OALLSTATUS = ''.
ELSE.
  TRANSLATE I_OALLSTATUS TO UPPER CASE.
ENDIF.

IF I_INVCSTATUS IS INITIAL.
  I_INVCSTATUS = '%'.
ELSEIF I_INVCSTATUS = 'X'.
  I_INVCSTATUS = ''.
ELSE.
  TRANSLATE I_INVCSTATUS TO UPPER CASE.
ENDIF.

IF I_BLDOC IS INITIAL.
  L_ITMNUM = '000010'.
ENDIF.


SELECT * FROM ZCA_BILLINGDOC_V INTO CORRESPONDING FIELDS OF TABLE ET_BILLINGDOC
                               WHERE SD_DOC      LIKE L_SDDOC
                                 AND DL_DOC      LIKE L_DLDOC
                                 AND BL_DOC      LIKE L_BLDOC
                                 AND SD_NUM      LIKE L_ITMNUM
                                 AND DL_NUM      LIKE L_ITMNUM
                                 AND BL_NUM      LIKE L_ITMNUM
                                 AND COMPANY     LIKE I_COMPANY
                                 AND SALES_ORG   LIKE I_SALESORG
                                 AND PAYER       LIKE I_PAYER
                                 AND SOLD_TO     LIKE I_SOLDTO
                                 AND MATNR       LIKE I_MATERIAL
                                 AND OALL_STATUS LIKE I_OALLSTATUS
                                 AND INVC_STATUS LIKE I_INVCSTATUS
                                 AND DOC_DATE      IN T_DOCDATE
                               ORDER BY DOC_DATE DESCENDING.
                               .


ENDFUNCTION.
