FUNCTION ZCA_SALESORDER_GETLIST .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_CUSTOMER) TYPE  KUNNR OPTIONAL
*"     VALUE(I_VBELN) TYPE  VBELN OPTIONAL
*"     VALUE(I_DLVBLK) TYPE  LIFSK OPTIONAL
*"     VALUE(I_STATUS) TYPE  UVALL OPTIONAL
*"     VALUE(I_DOCDATE) TYPE  ZCA_DOCDATE_WA OPTIONAL
*"     VALUE(I_ITMNUM) TYPE  POSNR OPTIONAL
*"     VALUE(I_MATNR) TYPE  MATNR OPTIONAL
*"     VALUE(I_REJECT) TYPE  ABGRU OPTIONAL
*"  EXPORTING
*"     VALUE(ET_SO_LIST) TYPE  ZCA_SALESORDER_TT
*"  TABLES
*"      T_DOCDATE TYPE  ZCA_DOCDATE_TT OPTIONAL
*"----------------------------------------------------------------------



"DATA : I_DOCDATE TYPE ZCA_DOCDATE_WA.

I_DOCDATE-SIGN = 'I'.
I_DOCDATE-OPTION = 'BT'.

IF I_DOCDATE-SALES_DATE_LOW IS INITIAL.
  I_DOCDATE-SALES_DATE_LOW = '00000000'.
ENDIF.

IF I_DOCDATE-SALES_DATE_HIGH IS INITIAL.
  I_DOCDATE-SALES_DATE_HIGH = '99991231'.
ENDIF.


APPEND I_DOCDATE TO T_DOCDATE.
CLEAR I_DOCDATE.



DATA:   L_CUSTOMER    TYPE  CHAR11  ,
        L_DLVBLK      TYPE  CHAR3 ,
        L_ITMNUM      TYPE  CHAR7 ,
        L_MATNR       TYPE  CHAR41,
        L_REJECT      TYPE  CHAR3,
        L_VBELN       TYPE CHAR11.




IF I_CUSTOMER IS INITIAL.
  L_CUSTOMER = '%'.
ELSE.
  CONCATENATE I_CUSTOMER  '%'   INTO  L_CUSTOMER.
  TRANSLATE L_CUSTOMER TO UPPER CASE.
ENDIF.



IF I_DLVBLK IS INITIAL.
  L_DLVBLK = '%'.
ELSEIF I_DLVBLK = 'X'.
  L_DLVBLK = ''.
ELSE.
  CONCATENATE I_DLVBLK    '%'   INTO  L_DLVBLK.
  TRANSLATE L_DLVBLK TO UPPER CASE.
ENDIF.


IF I_REJECT IS INITIAL.
  L_REJECT = '%'.
ELSEIF I_REJECT = 'X'.
  L_REJECT = ''.
ELSE.
  CONCATENATE I_REJECT    '%'   INTO  L_REJECT.
  TRANSLATE L_REJECT TO UPPER CASE.
ENDIF.



IF I_STATUS IS INITIAL.
  I_STATUS = '%'.
ELSE.
  TRANSLATE I_STATUS TO UPPER CASE.
ENDIF.

IF I_ITMNUM IS INITIAL.
  L_ITMNUM = '%'.
ELSE.
  L_ITMNUM = I_ITMNUM.
ENDIF.

IF I_MATNR IS INITIAL.
  L_MATNR = '%'.
ELSE.
  CONCATENATE I_MATNR     '%'   INTO  L_MATNR.
  TRANSLATE L_MATNR TO UPPER CASE.
ENDIF.




IF I_VBELN IS INITIAL.
  L_VBELN = '%'.
  L_ITMNUM = '000010'.
ELSE.
  SHIFT I_VBELN LEFT DELETING LEADING '0'.
  IF STRLEN( I_VBELN ) < 10.
    CONCATENATE '%' I_VBELN '%' INTO L_VBELN.
  ENDIF.
ENDIF.

SELECT *  FROM ZCA_SALESORDER_V INTO CORRESPONDING FIELDS OF TABLE ET_SO_LIST
       WHERE SOLD_TO    LIKE L_CUSTOMER "고객
        AND  DOC_DATE   IN   T_DOCDATE    "IN T_DOCDATE  "문서기간
        AND  SD_DOC     LIKE L_VBELN    "문서번호
        AND  DLV_BLOCK  LIKE L_DLVBLK   "배송 블락(ZA:확인)
        AND  DOC_STATUS LIKE I_STATUS   "문서 상태
        AND  ITM_NUMBER LIKE L_ITMNUM   "아이템인덱스
        AND  MATERIAL   LIKE L_MATNR
        AND  REASON_REJ LIKE L_REJECT
        ORDER BY DOC_DATE DESCENDING
        .




ENDFUNCTION.
