FUNCTION ZCA_SALESORDER_CREATE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_VBELN) TYPE  VBELN OPTIONAL
*"     VALUE(I_REQDAT) TYPE  EDATU_VBAK OPTIONAL
*"     VALUE(I_CUSTOMER) TYPE  KUNNR
*"     VALUE(IT_ORDERITEMS) TYPE  ZCA_IN_SALESORDER_TT OPTIONAL
*"  EXPORTING
*"     VALUE(E_MESSAGE) TYPE  BAPI_MSG
*"     VALUE(E_ERROR) TYPE  BAPI_MSG
*"     VALUE(E_VBELN) TYPE  VBELN
*"  TABLES
*"      T_RETURN STRUCTURE  BAPIRET2 OPTIONAL
*"      T_ORDER_ITEMS_IN STRUCTURE  BAPISDITM OPTIONAL
*"      T_ORDER_PARTNERS STRUCTURE  BAPIPARNR OPTIONAL
*"      T_ORDER_SCHEDULES_IN STRUCTURE  BAPISCHDL OPTIONAL
*"      T_ORDER_KEYS STRUCTURE  BAPISDKEY OPTIONAL
*"----------------------------------------------------------------------

        "Sales Doc Data
  DATA: L_SALESDOCUMENTIN  TYPE  BAPIVBELN-VBELN,

        W_ORDER_HEADER_IN  TYPE  BAPISDHD1,

        W_RETURN           TYPE BAPIRET2,

        "Primary Key Data
        W_ORDER_KEYS       TYPE BAPISDKEY,

        "Material Data
        W_ORDER_ITEMS_IN   TYPE  BAPISDITM,

        "Partner Data
        W_ORDER_PARTNERS   TYPE BAPIPARNR,

        "Scheduling Data
        W_SCHEDULES_IN     TYPE BAPISCHDL,

        L_MATNR            TYPE MATNR,
        L_MATNR1           TYPE MATNR,
        L_KUNNR            TYPE KUNNR,
        L_LIFNR            TYPE LIFNR,
        L_COUNT            TYPE syst_fmkey,
        L_POSNR            TYPE POSNR VALUE '0'.


  CLEAR: W_ORDER_HEADER_IN,
         W_ORDER_PARTNERS,W_ORDER_ITEMS_IN,
         W_SCHEDULES_IN.


  REFRESH: T_ORDER_PARTNERS[],T_ORDER_ITEMS_IN[],
           T_ORDER_SCHEDULES_IN[],T_RETURN[].



  "Sales Order Document Type
  W_ORDER_HEADER_IN-DOC_TYPE   = 'ZCA'.   "I_DOCTYPE.

  "Sales Organization
  W_ORDER_HEADER_IN-SALES_ORG  = 'A001'.  "I_SALESORG.

  "Distribution Channel
  W_ORDER_HEADER_IN-DISTR_CHAN = '10'.    "I_DISTCHN.

  "(Product) Division
  W_ORDER_HEADER_IN-DIVISION   = 'ZA'.    "I_DIVISION

  "Company Code
  W_ORDER_HEADER_IN-COMP_CDE_B = 'A001'.  "I_COMPANYCODE.


  IF I_REQDAT IS INITIAL.
    I_REQDAT = SY-DATUM + 7.
  ENDIF.
  W_ORDER_HEADER_IN-REQ_DATE_H = I_REQDAT.



  "Customer Reference
  DATA: IS_CUSTREFNO TYPE CHAR35.
  CONCATENATE I_CUSTOMER SY-DATUM SY-UZEIT INTO IS_CUSTREFNO SEPARATED BY '_'.

  W_ORDER_HEADER_IN-PURCH_NO_C = IS_CUSTREFNO.

  "Customer Reference Date
  W_ORDER_HEADER_IN-PURCH_DATE = SY-DATUM.




  "Sold-To Party
  W_ORDER_PARTNERS-ITM_NUMBER = '000000'."L_POSNR.
  W_ORDER_PARTNERS-PARTN_ROLE = 'AG'.
  W_ORDER_PARTNERS-PARTN_NUMB = I_CUSTOMER. "L_KUNNR.
  APPEND W_ORDER_PARTNERS TO T_ORDER_PARTNERS.
  CLEAR: W_ORDER_PARTNERS.

  "Ship-To Party
  W_ORDER_PARTNERS-ITM_NUMBER = '000000'."L_POSNR.
  W_ORDER_PARTNERS-PARTN_ROLE = 'WE'.
  W_ORDER_PARTNERS-PARTN_NUMB = I_CUSTOMER. "L_LIFNR.
  APPEND W_ORDER_PARTNERS TO T_ORDER_PARTNERS.
  CLEAR: W_ORDER_PARTNERS.








  "Add Material
  DATA: WA_ORDERITEMS TYPE ZCA_IN_SALESORDER_WA.

LOOP AT IT_ORDERITEMS INTO WA_ORDERITEMS.

    L_POSNR   = L_POSNR + 10.

    W_ORDER_KEYS-DOC_NUMBER = WA_ORDERITEMS-SD_DOC.
    W_ORDER_KEYS-ITM_NUMBER = L_POSNR.

    W_ORDER_ITEMS_IN-ITM_NUMBER = L_POSNR.                  "'000010'.

    W_SCHEDULES_IN-ITM_NUMBER   = L_POSNR.                  "'000010'.

    W_ORDER_ITEMS_IN-MATERIAL   = WA_ORDERITEMS-MATERIAL.      "'ZCA-F01'.

    W_SCHEDULES_IN-SCHED_LINE = '0001'.
    IF WA_ORDERITEMS-REQ_QTY IS INITIAL.
      WA_ORDERITEMS-REQ_QTY = 5.
    ENDIF.

    W_SCHEDULES_IN-REQ_QTY      = WA_ORDERITEMS-REQ_QTY.    "Quantity

    W_ORDER_ITEMS_IN-PLANT      = 'A001'. "WA_ORDERITEMS-PLANT.      "Plant

    W_ORDER_ITEMS_IN-STORE_LOC  = 'ZCA'.  "WA_ORDERITEMS-STORE_LOC.  "Storage Location








    APPEND W_ORDER_KEYS TO T_ORDER_KEYS.
    CLEAR: W_ORDER_KEYS.

    APPEND W_SCHEDULES_IN TO T_ORDER_SCHEDULES_IN.
    CLEAR: W_SCHEDULES_IN.

    APPEND W_ORDER_ITEMS_IN TO T_ORDER_ITEMS_IN.
    CLEAR: W_ORDER_ITEMS_IN.
ENDLOOP.




  CLEAR : I_VBELN.

  "Call BAPI
  CALL FUNCTION 'BAPI_SALESORDER_CREATEFROMDAT2'
    EXPORTING
      SALESDOCUMENTIN  = I_VBELN
      ORDER_HEADER_IN  = W_ORDER_HEADER_IN
    IMPORTING
      SALESDOCUMENT    = L_SALESDOCUMENTIN
    TABLES
      RETURN              = T_RETURN
      ORDER_ITEMS_IN      = T_ORDER_ITEMS_IN
      ORDER_SCHEDULES_IN  = T_ORDER_SCHEDULES_IN
      ORDER_PARTNERS      = T_ORDER_PARTNERS
      ORDER_KEYS          = T_ORDER_KEYS
      .





  IF L_SALESDOCUMENTIN IS NOT INITIAL.
    CLEAR : I_VBELN.
    I_VBELN = L_SALESDOCUMENTIN.
    CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
      EXPORTING
        WAIT = 'X'.
    SHIFT L_SALESDOCUMENTIN LEFT DELETING LEADING '0'.
    CONCATENATE 'Sales Order(판매오더)' L_SALESDOCUMENTIN 'has been created(생성성공) !' INTO E_MESSAGE
    SEPARATED BY SPACE.
    E_VBELN = L_SALESDOCUMENTIN.
  ELSE.
    LOOP AT T_RETURN INTO W_RETURN.
      L_COUNT = L_COUNT + 1.
      CONDENSE L_COUNT.
      CONCATENATE E_ERROR L_COUNT '.' W_RETURN-MESSAGE ';' INTO E_ERROR.
    ENDLOOP.
  ENDIF.

ENDFUNCTION.
