FUNCTION ZCA_BUPACREDIT_CHANGE.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_PARTNER) TYPE  KUNNR
*"     VALUE(I_CREDITSEGMENT) TYPE  UKM_CREDIT_SGMNT
*"----------------------------------------------------------------------



*"테스트용으로 만든거 사용 ㄴ




DATA: IO_FACADE        TYPE REF TO CL_UKM_FACADE,
      IO_PARTNER       TYPE REF TO CL_UKM_BUSINESS_PARTNER,
      IO_BUPA_FACTORY  TYPE REF TO CL_UKM_BUPA_FACTORY,
      IO_ACCOUNT       TYPE REF TO CL_UKM_ACCOUNT,
      LW_BP_CREDIT_SGM TYPE UKM_S_BP_CMS_SGM.

DATA: LWA_UKM_S_BP_CMS TYPE UKM_S_BP_CMS.



IO_FACADE = CL_UKM_FACADE=>CREATE( I_ACTIVITY = CL_UKM_CNST_EVENTING=>BP_MAINTENANCE ).
IO_BUPA_FACTORY = IO_FACADE->GET_BUPA_FACTORY( ).


IO_PARTNER = IO_BUPA_FACTORY->GET_BUSINESS_PARTNER( I_PARTNER ).

IO_PARTNER->GET_BP_CMS( IMPORTING ES_BP_CMS =  LWA_UKM_S_BP_CMS ).
LWA_UKM_S_BP_CMS-RISK_CLASS = 'A'.
IO_PARTNER->SET_BP_CMS( LWA_UKM_S_BP_CMS ).


CALL METHOD IO_BUPA_FACTORY->GET_CREDIT_ACCOUNT
  EXPORTING
    I_PARTNER         = I_PARTNER
    I_CREDIT_SGMNT    = I_CREDITSEGMENT
  RECEIVING
    RO_CREDIT_ACCOUNT = IO_ACCOUNT.

IO_ACCOUNT->GET_BP_CMS_SGM( IMPORTING ES_BP_CMS_SGM = LW_BP_CREDIT_SGM ).
LW_BP_CREDIT_SGM-CREDIT_LIMIT   = '666666666.00'.
LW_BP_CREDIT_SGM-XCRITICAL      = 'X'.
LW_BP_CREDIT_SGM-LIMIT_CHG_DATE = SY-DATUM.
IO_ACCOUNT->SET_BP_CMS_SGM( EXPORTING IS_BP_CMS_SGM = LW_BP_CREDIT_SGM ).

IO_BUPA_FACTORY->SAVE_ALL( ).





ENDFUNCTION.
