FUNCTION ZCA_OUTBOUNDRY_GETLIST .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_CUSTOMER) TYPE  KUNNR OPTIONAL
*"     VALUE(I_SDDOC) TYPE  VBELN OPTIONAL
*"     VALUE(I_VBELN) TYPE  VBELN OPTIONAL
*"     VALUE(I_DOCDATE) TYPE  ZCA_DOCDATE_WA OPTIONAL
*"     VALUE(I_ITMNUM) TYPE  POSNR OPTIONAL
*"     VALUE(I_MATNR) TYPE  MATNR OPTIONAL
*"     VALUE(I_BILLSTATUS) TYPE  FKSTK OPTIONAL
*"     VALUE(I_OALLSTATUS) TYPE  GBSTK OPTIONAL
*"     VALUE(I_PICKSTATUS) TYPE  KOSTK OPTIONAL
*"     VALUE(I_GOODSTATUS) TYPE  WBSTK OPTIONAL
*"     VALUE(I_OALLBLOCK) TYPE  SPSTG OPTIONAL
*"     VALUE(I_BILLBLCOK) TYPE  FAKSK OPTIONAL
*"     VALUE(I_DELVBLOCK) TYPE  LIFSK OPTIONAL
*"  EXPORTING
*"     VALUE(ET_OD_LIST) TYPE  ZCA_OUTBOUNDRY_TT
*"  TABLES
*"      T_DOCDATE TYPE  ZCA_DOCDATE_TT OPTIONAL
*"----------------------------------------------------------------------

I_DOCDATE-SIGN = 'I'.
I_DOCDATE-OPTION = 'BT'.

IF I_DOCDATE-SALES_DATE_LOW IS INITIAL.
  I_DOCDATE-SALES_DATE_LOW = '00000000'.
ENDIF.

IF I_DOCDATE-SALES_DATE_HIGH IS INITIAL.
  I_DOCDATE-SALES_DATE_HIGH = '99991231'.
ENDIF.

APPEND I_DOCDATE TO T_DOCDATE.
CLEAR I_DOCDATE.




DATA:   L_CUSTOMER    TYPE  CHAR11  ,
        L_DELVBLOCK   TYPE  CHAR3 ,
        L_ITMNUM      TYPE  CHAR6 ,
        L_MATNR       TYPE  CHAR41,
        L_BILLBLCOK   TYPE  CHAR3,
        L_SDDOC       TYPE CHAR11,
        L_VBELN       TYPE CHAR11.


"고객번호
IF I_CUSTOMER IS INITIAL.
  L_CUSTOMER = '%'.
ELSE.
  CONCATENATE I_CUSTOMER  '%'   INTO  L_CUSTOMER.
  TRANSLATE L_CUSTOMER TO UPPER CASE.
ENDIF.


"판매문서번호
IF I_SDDOC IS INITIAL.
  L_SDDOC = '%'.
ELSE.
  SHIFT I_SDDOC LEFT DELETING LEADING '0'.
  IF STRLEN( I_SDDOC ) < 10.
      CONCATENATE '%' I_SDDOC '%' INTO L_SDDOC.
  ENDIF.
ENDIF.

"납품문서번호
IF I_VBELN IS INITIAL.
  L_VBELN = '%'.
ELSE.
  SHIFT I_VBELN LEFT DELETING LEADING '0'.
  IF STRLEN( I_VBELN ) < 10.
      CONCATENATE '%' I_VBELN '%' INTO L_VBELN.
  ENDIF.
ENDIF.








"아이템인덱스
IF I_ITMNUM IS INITIAL.
  L_ITMNUM = '%'.
ELSE.
  L_ITMNUM = I_ITMNUM.
ENDIF.

"자재번호
IF I_MATNR IS INITIAL.
  L_MATNR = '%'.
ELSE.
  CONCATENATE I_MATNR     '%'   INTO  L_MATNR.
  TRANSLATE L_MATNR TO UPPER CASE.
ENDIF.


"전체상태
IF I_OALLSTATUS IS INITIAL.
  I_OALLSTATUS = '%'.
ELSE.
  TRANSLATE I_OALLSTATUS TO UPPER CASE.
ENDIF.

"피킹상태
IF I_PICKSTATUS IS INITIAL.
  I_PICKSTATUS = '%'.
ELSE.
  TRANSLATE I_PICKSTATUS TO UPPER CASE.
ENDIF.

"G M 상태
IF I_GOODSTATUS IS INITIAL.
  I_GOODSTATUS = '%'.
ELSE.
  TRANSLATE I_GOODSTATUS TO UPPER CASE.
ENDIF.

"빌링상태
IF I_BILLSTATUS IS INITIAL.
  I_BILLSTATUS = '%'.
ELSE.
  TRANSLATE I_BILLSTATUS TO UPPER CASE.
ENDIF.

"모든 BLOCK 상태
IF I_OALLBLOCK IS INITIAL.
  I_OALLBLOCK = '%'.
ELSE.
  TRANSLATE I_OALLBLOCK TO UPPER CASE.
ENDIF.

"빌링 BLOCK 상태
IF I_BILLBLCOK IS INITIAL.
  I_BILLBLCOK = '%'.
ELSE.
  CONCATENATE I_BILLBLCOK    '%'   INTO  L_BILLBLCOK.
  TRANSLATE L_BILLBLCOK TO UPPER CASE.
ENDIF.

"배송 BLOCK 상태
IF I_DELVBLOCK IS INITIAL.
  I_DELVBLOCK = '%'.
ELSE.
  CONCATENATE I_DELVBLOCK    '%'   INTO  L_DELVBLOCK.
  TRANSLATE L_DELVBLOCK TO UPPER CASE.
ENDIF.





IF I_VBELN IS INITIAL.
  L_ITMNUM = '000010'.
ENDIF.


SELECT * FROM ZCA_OUTBOUNDRY_V INTO CORRESPONDING FIELDS OF TABLE ET_OD_LIST

         WHERE DOC_DATE         IN T_DOCDATE      "IN T_DOCDATE  "문서기간
          AND  SOLD_TO        LIKE L_CUSTOMER     "고객번호
          AND  SD_DOC         LIKE L_SDDOC      "판매문서번호
          AND  DL_DOC         LIKE L_VBELN        "납품문서번호
          AND  DL_NUM         LIKE L_ITMNUM      "아이템인덱스
          AND  MATERIAL       LIKE L_MATNR        "자재번호
          AND  OALL_STATUS    LIKE I_OALLSTATUS   "전체상태
          AND  PICK_STATUS    LIKE I_PICKSTATUS   "피킹상태
          AND  GOOD_STATUS    LIKE I_GOODSTATUS   "G M 상태
          AND  BILL_STATUS    LIKE I_BILLSTATUS   "빌링상태
          AND  ABLK_STATUS    LIKE I_OALLBLOCK    "모든 Block 상태
          AND  BBLK_STATUS    LIKE L_BILLBLCOK    "빌링 Block 상태
          AND  DBLV_STATUS    LIKE L_DELVBLOCK    "배송 Block 상태
          ORDER BY DOC_DATE DESCENDING
          .


*
*  SELECT * FROM VBAK INTO CORRESPONDING FIELDS OF TABLE ET_HEADER WHERE VBELN = I_VBELN.
*
*
*  SELECT * FROM VBAP INTO CORRESPONDING FIELDS OF TABLE ET_ITEMS
*         WHERE VBELN = I_VBELN.
*
*  SELECT * FROM VBKD INTO CORRESPONDING FIELDS OF TABLE ET_BUSINESS
*           WHERE VBELN = I_VBELN.


ENDFUNCTION.
