*&---------------------------------------------------------------------*
*& Report ZCALC_SEATS_26
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZCALC_SEATS_26.




DATA : BEGIN OF LS_DATA,
          CARRID   TYPE S_CARRID,
          CARRNAME TYPE S_CARRNAME,
          CONNID   TYPE S_CONN_ID,
          FLDATE   TYPE S_DATE,
          SEATSMAX TYPE S_SEATSMAX,
          SEATSOCC TYPE S_SEATSOCC,
          SEATSDIF TYPE S_SEATSMAX,
        END OF LS_DATA,
        LT_DATA LIKE TABLE OF LS_DATA
          WITH NON-UNIQUE KEY CARRID CONNID FLDATE.

DATA : LT_SCARR TYPE TABLE OF SCARR,
       LS_SCARR LIKE LINE OF LT_SCARR.




PARAMETERS : PA_CARR TYPE S_CARRID,
             PA_CONN TYPE S_CONN_ID.



SELECT * INTO CORRESPONDING FIELDS OF TABLE LT_SCARR
  FROM SCARR.


SELECT * INTO CORRESPONDING FIELDS OF TABLE LT_DATA
  FROM SFLIGHT
  WHERE CARRID = PA_CARR
    AND CONNID = PA_CONN.


LOOP AT LT_DATA INTO LS_DATA.
  CLEAR: LS_SCARR.
  READ TABLE LT_SCARR INTO LS_SCARR WITH KEY CARRID = LS_DATA-CARRID.
  LS_DATA-CARRNAME = LS_SCARR-CARRNAME.
  LS_DATA-SEATSDIF = LS_DATA-SEATSMAX - LS_DATA-SEATSOCC.
  MODIFY LT_DATA FROM LS_DATA.
ENDLOOP.

IF SY-SUBRC <> 0.
  MESSAGE '데이터가 없어용' TYPE 'I'.
  RETURN.
*ELSE.
*SORT LT_DATA BY SEATSDIF DESCENDING.
ENDIF.

CL_DEMO_OUTPUT=>DISPLAY( LT_DATA ).
