*&---------------------------------------------------------------------*
*& Report ZTABSTRIP_PRG_26
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZTABSTRIP_PRG_26.


DATA: GS_flight TYPE sflight.

SELECTION-SCREEN BEGIN OF SCREEN 110 as SUBSCREEN.
  PARAMETERS: pa_car TYPE sflight-CARRID,
              pa_con TYPE sflight-CONNID.
SELECTION-SCREEN END OF SCREEN 110.

SELECTION-SCREEN BEGIN OF SCREEN 120 as SUBSCREEN.
  SELECT-OPTIONS: SO_FDT FOR GS_flight-FLDATE.
SELECTION-SCREEN END OF SCREEN 120.

SELECTION-SCREEN BEGIN OF SCREEN 130 as SUBSCREEN.
  PARAMETERS: PA_ID TYPE SBOOK-CUSTOMID,
              PA_ALL RADIOBUTTON GROUP RB1,
              PA_NAT RADIOBUTTON GROUP RB1,
              PA_INT RADIOBUTTON GROUP RB1.
SELECTION-SCREEN END OF SCREEN 130.



SELECTION-SCREEN BEGIN OF TABBED BLOCK STRIP FOR 4 LINES.
  SELECTION-SCREEN TAB (20) tab1 USER-COMMAND com1 DEFAULT SCREEN 110.
  SELECTION-SCREEN TAB (20) tab2 USER-COMMAND com2 DEFAULT SCREEN 120.
  SELECTION-SCREEN TAB (20) tab3 USER-COMMAND com3 DEFAULT SCREEN 130.
SELECTION-SCREEN END OF BLOCK STRIP.

INITIALIZATION.
  TAB1 = 'CONNECTION'.
  tab2 = 'FLIGHTS'.
  tab3 = 'BOOKING'.
  STRIP-ACTIVETAB = 'COM2'.
  STRIP-DYNNR = 120.



START-OF-SELECTION.
  SELECT SINGLE * INTO GS_FLIGHT
    FROM SFLIGHT
    Where CARRID = PA_CAR
      AND CONNID = PA_CON
      AND FLDATE IN SO_FDT.


WRITE:/ GS_flight-CARRID,
        GS_flight-CONNID,
        GS_flight-FLDATE,
        GS_flight-SEATSMAX,
        GS_flight-SEATSOCC.
